#!/usr/bin/env bash
# Generate a markdown results matrix from cross-sdk-diff.sh --json output.
# Usage: ./generate-matrix.sh > RESULTS.md
DIR="$(cd "$(dirname "$0")" && pwd)"

# Run diff (exits non-zero when divergences found, that's expected)
JSON=$("$DIR/cross-sdk-diff.sh" --json 2>/dev/null) || true

echo "$JSON" | python3 -c "
import sys, json

raw = sys.stdin.read().strip()
if not raw:
    print('No results.')
    sys.exit(0)

data = json.loads(raw)
languages = list(data[0]['results'].keys())

print('# Cross-SDK Differential Test Results\n')
print(f'**Languages tested:** {\", \".join(languages)}')
print(f'**Total tests:** {len(data)}')
agree_count = sum(1 for d in data if d['agree'])
diverge_count = len(data) - agree_count
print(f'**Agree:** {agree_count} | **Diverge:** {diverge_count}\n')

header = '| Test | ' + ' | '.join(languages) + ' | Status |'
sep = '|------|' + '|'.join(['------'] * len(languages)) + '|--------|'
print(header)
print(sep)

for entry in data:
    test = entry['test']
    status = 'AGREE' if entry['agree'] else '**DIVERGE**'
    values = []
    for lang in languages:
        val = entry['results'].get(lang, '—')
        val = str(val)
        if len(val) > 30:
            val = val[:27] + '...'
        val = val.replace('|', '\\\\|')
        values.append(f'\`{val}\`')
    print(f'| {test} | ' + ' | '.join(values) + f' | {status} |')

print(f'\n*Generated by cross-sdk-diff.sh*')
"
