// C-REC data payload generator for SEP-3004 PR-comment reference.
//
// Produces the raw C-REC data (KAT verification, 11-row side-by-side
// table, five producer-requirement vectors) as a markdown file that can
// be linked from a PR comment on modelcontextprotocol#3004 so the comment
// stays small.
//
// Canonicalizers and fixture inputs are imported from ../harness.ts (which
// in turn imports GIF's canonicalize from ../vendored/gif/ and this repo's
// canonicalizeValue from src/). This file only formats output.
//
// Run:
//   npx tsx test/vectors/c-rec/reports/build-comment-payload.ts
//     -> prints to stdout
//   npx tsx test/vectors/c-rec/reports/build-comment-payload.ts --write
//     -> writes to test/vectors/c-rec/reports/SEP-3004-comment-payload.md
//
// CI verifies the committed file matches a fresh regen (drift-gate).

import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { canonicalize as gifCanonicalize } from "../vendored/gif/audit-record-contract.js";
import {
  KAT_INPUT,
  KAT_EXPECTED,
  buildTableSection,
  buildVectorSection,
} from "../harness.js";

const sha256 = (s: string): string =>
  createHash("sha256").update(s).digest("hex");

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = join(HERE, "SEP-3004-comment-payload.md");

function buildPayload(): string {
  const katHash = sha256(gifCanonicalize(KAT_INPUT));
  const katOk = katHash === KAT_EXPECTED;

  const header = [
    "# SEP-3004 C-REC data (raw)",
    "",
    "Auto-generated by `test/vectors/c-rec/reports/build-comment-payload.ts`.",
    "Do not edit by hand. Regenerate with `npm run c-rec:report`.",
    "",
    "CI verifies this file matches a fresh regeneration on every push. If",
    "the last-updated marker below drifts from the committed value, the",
    "build fails.",
    "",
    "## KAT verification (SEP-3004 sealed hash)",
    "",
    "GIF's `canonicalize()` (used verbatim from the vendored source at",
    "`test/vectors/c-rec/vendored/gif/audit-record-contract.ts`, pinned to",
    "commit `e1f02a95506e81e7766c3ba3a684ecad7cfff12f`) applied to the",
    "sealed KAT_INPUT reproduces the published `KAT_HASH_CG` byte-for-byte.",
    "Any divergence in the comparison tables below is real, not",
    "implementation drift on the mcp-audit-gateway side.",
    "",
    "```",
    `computed: ${katHash}`,
    `expected: ${KAT_EXPECTED}`,
    `match:    ${katOk ? "YES" : "NO — investigate immediately"}`,
    "```",
    "",
  ].join("\n");

  return [
    header,
    buildTableSection(),
    "",
    buildVectorSection(),
    "---",
    "",
    "Regenerate with `npm run c-rec:report`. Fixture inputs and canonicalizer imports live in `test/vectors/c-rec/harness.ts`; this file only formats output.",
    "",
  ].join("\n");
}

const payload = buildPayload();
if (process.argv.includes("--write")) {
  writeFileSync(OUT_PATH, payload);
  console.log(`wrote ${OUT_PATH} (${payload.length} bytes)`);
} else {
  process.stdout.write(payload);
}
